---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: botkube
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/infracloudio/botkube/tree/develop/helm/botkube
