apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: client
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: client
    spec:
      containers:
        - env:
            - name: CHOKIDAR_USEPOLLING
              value: "true"
          image: client
          name: client
          resources: {}
          stdin: true
          volumeMounts:
            - mountPath: /app/node_modules
              name: client-claim0
            - mountPath: /app
              name: client-claim1
      restartPolicy: Always
      volumes:
        - name: client-claim0
          persistentVolumeClaim:
            claimName: client-claim0
        - name: client-claim1
          persistentVolumeClaim:
            claimName: client-claim1
status: {}
