version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "mcclaren00/ladder-toolbox-server"
    ports:
      - "4000:4000"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "mcclaren00/ladder-toolbox-client"
    ports:
      - "3000:3000"
