---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  CLUSTER_DIR: "{{.PROJECT_DIR}}/cluster"
  ANSIBLE_DIR: "{{.PROJECT_DIR}}/provision/ansible"
  TERRAFORM_DIR: "{{.PROJECT_DIR}}/provision/terraform"
  HACK_DIR: "{{.PROJECT_DIR}}/setup"

dotenv: [".config.env"]

env:
  KUBECONFIG: "{{.PROJECT_DIR}}/provision/kubeconfig"

includes:
  ansible: .taskfiles/AnsibleTasks.yml
  cluster: .taskfiles/ClusterTasks.yml
  precommit: .taskfiles/PrecommitTasks.yml
  terraform: .taskfiles/TerraformTasks.yml
  # hack: .taskfiles/HackTasks.yml

tasks:

  init:
    desc: Install dependancies through brew
    cmds:
      - brew install {{.DEPS}} {{.CLI_ARGS}}
    preconditions:
      - sh: command -v brew
        msg: install homebrew
    vars:
      DEPS: >-
        age
        ansible
        direnv
        fluxcd/tap/flux
        gitleaks
        go-task/tap/go-task
        helm
        ipcalc
        jq
        kubernetes-cli
        kustomize
        pre-commit
        prettier
        sops
        stern
        terraform
        yamllint
        yq
        k3sup
        gcc
        go
        aylei/tap/kubectl-debug

  workstation:
    desc: Install dependancies, for workstations through brew
    cmds:
      - brew install {{.DEPS}} {{.CLI_ARGS}}
    preconditions:
      - sh: command -v brew
        msg: install homebrew
    vars:
      DEPS: >-
        direnv
        gitleaks
        go-task/tap/go-task
        pre-commit
        prettier
        yamllint
        gcc
        go
      # aylei/tap/kubectl-debug

  verify:
    desc: Verify env settings
    cmds:
      - ./configure --verify

  configure:
    desc: Configure repository from env settings
    cmds:
      - ./configure