# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:NE3EpjZAzaZ2lbH/P+rwh3LPBdk=,iv:GIZ5bRxVBiyjhpFunaZv4mGdr3qw6COutBPF5vOmrV0=,tag:G9KUJqtDPTo7NA0KoIwOSQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:Y1AfTAJrN0435+M6H46mQ+hsoGsRwKD1EYz2S+LJII3LpESTkg==,iv:E7MsJHN6z7olLmISHPrfCzpqDiGsSj8xO66wJ6y7Xn8=,tag:m5Hr5Lgv7Y85ePQmNr5hZA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:EuF+5+nr4/rVHJT4oF51he5Yyu6I,iv:qpFmFzIAxu2k9zJV/9LJVwlWJBIB5ocvkfD5FuCrO04=,tag:SrpLonpBQIf7Xoqzcx4qTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fk8cpzq0vpmeyrs3x09xdnccfhmcfx65yyf35a0kka9twn8drywscfy3dp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVndLdGpTditzdEpxU3VL
            U1hpYzg5Z0drcTU2MmFybUxjcEdnM0ZxbmhzCmZFMC9PZDlhZlBGMGxocUN2bHB0
            NXFhZnRzZmZCM3VhbVFaS0h4SVVRRVkKLS0tIHRZY0pNMXJhcS9YQlQyTlAwczgw
            V1N5dDdiS21VamtFWHp3aDhqYXArVXMK0c+KhlOn/qASuXk02K2m35jQ/aMy6HmO
            Yt8M/JX1G0c3NxroDTZa7ws7F/iU4q7i6QkPbyjnFJiRLV1DOabPWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-24T00:30:57Z"
    mac: ENC[AES256_GCM,data:rMGU9upBbI+KsBeMUuVSxqnAUWszZSXeMKNuiKkV0hTxq9ht3VR+0SqzRPcNyzOzqK2BpBwssX2yWnp909yKoCtIC+KFSnSyvAEgeC1XxR2hwIqgUWjPQiJve8WCfBRDrtGgDC9EU/LIN+lwBawCyVmeXxYnuDISbzP4EqSPiSA=,iv:nw/23PaL+gQhCRoIN2ied0jakUC5uHxMRwsjjtNPfVM=,tag:tRltN88TlVDer0Swq/O+1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
