# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: mcclaren00@gmail.com
    CLOUDFLARE_APIKEY: b6b61527306209ed709053926bc004c567e02
    CLOUDFLARE_RECORD_NAME: icoolyousuck.com
