# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:QoPydTruXAc0/pCl7dQw6zmZ3pY=,iv:yFlNARUQxj3LVGED8kH8U1+3y30hqkxT3uK8seUlKLk=,tag:CcFizsuJsZ8UFjzlhiSyrw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:b78w/3OiEjdKMTOJnwsRsAxZh6myd+CF+UGkQY4jVxC899RAIQ==,iv:MK6Cd1EnC61qUsiWElcUFt84Sur63q30FgbK8e58wWA=,tag:6l8bBqQcUG9ybtQYfiusHA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:7tfZ0RDU9AZh05ATEsFqoJshX7xL,iv:HjPRhOXwvaMsrC0O/n2JbPjs9X1v2BqCk0G4B5vfkvE=,tag:WHxDDv0TCbMjdpWBTy9GJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m3hvf7e58692g982nvz4zul9f2ck5azhnfjzr3pngj4esv532c9q022x5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNUhCVVJKUnpRTFNlY01i
            ck9vdHlYR2t1b3FwL3kvRWJheFdNZjd6WWxRCm1oTVZ5WWpUcERzdm5iTkcyck1J
            cXN5QmhPK3hzUmlmV0JNK3dScDZGQTQKLS0tIHlWUEc3Q0w2bTZaeEYxVnZ6b01m
            RjUzTFd5K3UvTUQxMk5aQTN2SE1uak0K9l95BFIslBx90tt1a49kgneEA7NQxJO8
            OSE8lgc1jfP2KHLDR5YXKlrkWoK5aeYMgl4B3DjV/NPURyfKuPVVqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-13T04:04:32Z"
    mac: ENC[AES256_GCM,data:iwD9Z4ptACHceeS41jBDw9PXJO7etCKUIDl0Eiafu3bUsr8/OR7al0AuJfiphiHKiWShlGPIH24y3m5cOROlB4HGCZ50e+Ma+JC5SvqtW7O1Nh2m+oo5r37CDz/RX2zJWmPVscC6+TmuTL/yVv28B57QAYDBK7vPiL5vRFieOK4=,iv:T4wB8OB/k3jDcJ6o4LbsbjFOVYjQ4jcTQAytPUZ1Ufg=,tag:sKWUY7oEPd0nG+NJtJYIqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
