# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:RIDHk1fN3WS9C5WyW+TQwV23m0c=,iv:XhNFlo+5rJ/YHut1gcsL12VG4LShqhBr8xtczENkX9M=,tag:dq1dOU2NSONWtprPFHFOTA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:IkmOmhe6AMx+rPV+aGvd5CyCLhLldDIhwuQkZr1WOsd8jyd1Fw==,iv:csk1/xXR/5DXtjyCUIyBUg37lZwggHroPGpCZERZZ5A=,tag:PSqvaH98eJF9jw6oJ2aKNw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:nqQfdjPo8cRSXJFr69WUxg==,iv:DhASj+FH1P9xan8wqxzALt3ozHHMEnHbXU/GNW6+FRk=,tag:ZvyGs9lpspo+gHuxvjxUVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m3hvf7e58692g982nvz4zul9f2ck5azhnfjzr3pngj4esv532c9q022x5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNFRUamtsMDZpUXFNVDhk
            Wk01b09Fckx3TC8wQi9IU2RoVlZrM3daR3hZCkIvWnY2VFpzSXU1K0VXNmJ1VXl0
            Qno0QllLK01QTm8vRGZZS0hRRXVBYk0KLS0tIEJSakJ6dmVkanJnbCtUQ2VuWjJa
            d1NRUWJvMnBoNGhsYWVBL3JxeUsySzQK3hUUA1kU0H8+8HuypVlUS1sbLSfUP/qv
            kxm4fyVvMwqLw3T8MX8+0vZcIliyLEkL215XHE8ImqJjmhiWtW0HPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-11T22:11:04Z"
    mac: ENC[AES256_GCM,data:PHCqmDbWYb4+13g57nB7qmm+zFyl2RsrD7DO3lgAF6LDcMIWox5jjYup5VUWtCtlNDoIPIwzf290xGJd9Qme7Uu768E22Ig5y8Pc2DXvNPEjsHaljGkbkwSTfkrHJjZGiAmz8zqCU+pCAYEpKM8K6kPL9EssW9NgzJ7FcYMrND0=,iv:NSRZVR4tRLobe5WTsvnzFJMbGXBGi4Gmb0/y8O12/3M=,tag:IkkEZX7rLBWs9Uq2R2HV2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
