# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ZNn1GbMR3TzAKshsPSaIqNu8+oE=,iv:dd2S9U7cJXQImkDu1cEEvyk4tde0oG5lTtlh2rDGYzU=,tag:WN4NstK9OcSjM+UBp6oufw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:qDS0/JOkAHjv6JyFa52nl+/SzFni8812eH+U0O+NEne6K0A6WA==,iv:HP7BZ4ytUuTuOQVd+0EqRuHZfU0tJuDYu94hlgwAQ8k=,tag:nDYueWsyfj5t4RSUQZaCNw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:+DU1GlVMl0380M0w6Q2B4vx2MRIZ,iv:7VENolBxlcSiumnaeBdcBO6CAIHt40MbRSdUZ0ZK+R4=,tag:/9lInqFNmcDw0/Pk01+z0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vd5j7kge9c8w8t3aj3ekk4gp98fxhaqaptj224yl9aq3nekns30qneex5d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORkhhWjRDd2ptSFVhR3A0
            TFRBMDBEc3Q1OEIxYW1tQWpVMHNyNjdZajFNClI4UmdoQzdCRTdpWi8wSjFYVDRu
            UUdidTBWZnZFUWlLM0lpWjlnalcrRHcKLS0tIHJhSXZHaEp6OVd2aSs5d2ZIUzFW
            ZnNBZXowT2F5dnRXSk0xMy9yRmwwU1EKCHd0piold9dMCqEApZ4EVoB/vIhDCdIV
            GddTL+QKQrdRVJE+itZUMz600Z4OlXZDeRoEHKn0HZtZBvP8Of8tSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-05T23:53:05Z"
    mac: ENC[AES256_GCM,data:5aw46keQqt1/2JylKLbIQEE1I1qyziiu4oXb6FSslw1mgwDXHRqKNA7RLMaNV4RJnL3LRK0CtdkZ0i+DjelgTQaChcdmz5VXo+mbhqInSqUPr3KKpoDKGEsuRZGsz8J3tXzN5QKpJkXlwUPFX/5oFySRExG9CJZhdLMN04TKmkw=,iv:jKdop18E5b5xJtGFce2aq+jhDo8RnN9UL+p8IFBKYwk=,tag:RQQqK1JUs192MLsGB1G/1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
