# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:NJnWwTZ5pWSf3dDpkF/b3xoPW2g=,iv:zHqsqhNIFohKoOLeU+9a+WHF18ckEPT9H2VmwRpU/q0=,tag:NCBgx1ojGbtleELsuCoanw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:LWYEee9GGHg9rfT/LiSowXaK/uyHhY+ju8jrzpSP3m3Z3iCwOw==,iv:vmyVHRcaNuvIcE9msiud/CswcbWUAL41kEcCrGRL5Fg=,tag:1JQpOefNmdtp+FN7hONCEQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:AgD7ZM4I+I1FgkHCTAzTV3JbY5ct,iv:8VxOxRqaPS+4iHcs15prc0KdCEiFxaP6SZ+3o/ahRds=,tag:MWrG9nA8/8f978uQXihOXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m3hvf7e58692g982nvz4zul9f2ck5azhnfjzr3pngj4esv532c9q022x5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMENtT2pPRHlWYi9PRE9I
            L2ZBZUJiSWJDTUdGdUt5VUFITFgwR2JEeTJnCkZlbEwvUWc2SXFkVk9IU0ZhS0NQ
            ajVXR252YmU1dU9haER4Ly9hNG9rS1UKLS0tIEM0YVY0c1hvclkwZ0cvVDhKbkFU
            dERRTi8zc3M2RENEZ1cySHQ1REpiQUUKXo1loohWjTeXp9VPFYci/sBfUvQt+7LX
            uQZby8KpcIliErB/g36dYZN1mSr+qp6xh2C980kIMvFbbItywHxk1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-13T18:03:04Z"
    mac: ENC[AES256_GCM,data:GB09eFIpEh9RHkYXLNkzq8hSpYnXarHopJetjdH5kG1YmdnCmokPRUY82+r927f/VRjkgVBg5VxsXUAFqheWqzPpyZz8dF2JYRgBe/lWBamDCQu1VWkWN1qA2aY+7m/Xl5FVqnYsHtdsU373/XYzBG0csIkVfR/iyG2QUUMy8Ew=,iv:p9Sop+6+7w3ahrrU3ahHjz31SjQCpzc3BPdZVtsVA6k=,tag:mDHTpnV38MaKwdOlah8ADw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
