---
- hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
  tasks:
    - name: check if cluster already installed
      ansible.builtin.stat:
        path: "/etc/rancher/k3s/config.yaml"
      register: k3s_check_installed
      check_mode: false

    - name: set manifest facts 
      ansible.builtin.set_fact:
        k3s_server_manifests_templates: []
        k3s_server_manifests_urls: []
      when: k3s_check_installed.stat.exists
    hosts: localhost 
      - name: Installing K3s
        ansible.builtin.shell:
          cmd: ./bootstrap-cluster.sh
          chdir: ../../../setup
        delegate_to: 127.0.0.1

    - name: remove templates 
      ansible.builtin.file:
        path: "{{ k3s_server_manifests_dir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
        state: absent
      loop: "{{ k3s_server_manifests_templates }}"
      when:
        - k3s_server_manifests_templates
        - k3s_server_manifests_templates | length > 0

    - name: remove manifest urls
      ansible.builtin.file:
        path: "{{ k3s_server_manifests_dir }}/{{ item.filename }}"
        state: absent
      loop: "{{ k3s_server_manifests_urls }}"
      when:
        - k3s_server_manifests_urls
        - k3s_server_manifests_urls | length > 0