---
- hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: nuke

- name: Reboot Servers
  hosts: node, master
  gather_facts: false
  become: true
  tasks:
    - name: Reboot machine
      reboot:
        reboot_timeout: 200
