---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: info-discord
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      namespace: flux-system
      name: flux-system
    - kind: HelmRelease
      namespace: default
      name: "*"
    - kind: HelmRelease
      namespace: kube-system
      name: "*"
    - kind: HelmRelease
      namespace: monitoring
      name: "*"
    - kind: HelmRelease
      namespace: networking
      name: "*"
    - kind: HelmRelease
      namespace: system-upgrade
      name: "*"
  exclusionList:
    - "reconciliation failed: Operation cannot be fulfilled on .*:
      the object has been modified;
      please apply your changes to the latest version and try again"