# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:jBJckhW3eeKFRi3FrlvF8Q==,iv:CI7LHY7S8QfhlTxHPi7cxlXZ9HEcxgB+c9HQ7lx7bKI=,tag:51vhLrHxxVIFCZwE65caxw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:jf2PBBQl22JNIyyaJnHsLF1h6Vo=,iv:5aSoMCbrV+AkMLnPF2qdF1YFOosnpzyqvH045ba0Zrg=,tag:3nwZs23uFtoNZbvgAli10w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m3hvf7e58692g982nvz4zul9f2ck5azhnfjzr3pngj4esv532c9q022x5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UWlpR2JyUk0yQVVmamxm
            SlRRRDgwV0xGOW9QVnJWYUdRSDd1amJjbEJZCkZpU0Z1bDExNythMjFYVCtGVEkx
            ekQyZ2lpQ0gyUVBkMXhjMG9TakVqL28KLS0tIGFVTkRhZ2NkUEt2VU9GcUlTVHlr
            TXVLZVIvYm9rYTBURU45M0RxQ1BaWlkK0EdAizWcDlhgBfib/WsxElOnwovuqTjN
            /xsISrYFYtcqC7gedtwEjRroGUBm2lSNScuy0UnR8dhjw6yE71xLyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-13T04:04:32Z"
    mac: ENC[AES256_GCM,data:xeZgxLjWwWRProJqgm7l/7HqGHCTuk5Y39ghfFThnP8YbbRM68KVjzLcWYtei4ikuoT6qRZ7LpltNHjCf5Il5X11ZdKeqztJ0xD6u8cysI3kj/WI1jP4tFDD6G2SQqpAFdAo4n2qhUUoR4SszvcUxYCr1tEA1/V02cr/aAoheSA=,iv:MWFr8L9PCOXfnj9dknX+mqOldsZuGcsZpqK+dMJ+ny4=,tag:Wv9YpqesSvTGfPrAJA3WSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
