# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ogRrEYD5+QHQaGLyZnFwdr8z6Rl0yEvGO8QBudI6ZETpaBtWdOCVCg==,iv:QuhC+qL/blNGJWc7B++II++Dw1y1eiXxjUXP7a94Kxk=,tag:fzItyF7KWtfE3kOMrFgGFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m3hvf7e58692g982nvz4zul9f2ck5azhnfjzr3pngj4esv532c9q022x5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNKzFDOGlGN3RhV0JqcVlr
            cjdKNTNSc0hBcWVmM1RkL3B5L1RNSkRyS2lNCll1Zkt3dW9wU0RTSDhycXlRZjdk
            RVI3VjlMdWh1bVc1OENNeG9YZ3drVUEKLS0tIGU2YUkyaUJEaHVsS2VUa2Q4bER6
            QVEyRHArSTliMnpOMTlSZVlaUUMvMUkKiqUO769IhthNPcY9Rz8xwALCTEmZVASM
            0eWD2k/d08nol3NDNO8sqHBxZhhuua4l944mc+MEuFmNPCXNAbbxDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-09T18:39:48Z"
    mac: ENC[AES256_GCM,data:gI5Cw5bjaO7UWcy9XtvCavjbJIzICCIU5WugAV9fi5nqcYoxLDAaS5Y7U7UXoS+8MDVuv8KmGwSCbLO5qpbglzZ/+2CLV8sPykEOpkIoCfsgLeglYJnKKEHMIq7Kf6xCtkI88tU+TFpbMBJ5QI7oyp7kjHdLVaCbkOgKjBgC8ms=,iv:1EuG7OHEet7Os3+Cw28PQADiDT47aB9aKd3LSxYfKBE=,tag:9/zVTweFvDeoNWPWaKaz9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
