---
apiVersion: v1 
kind: Service
metadata:
  name: ladder-client
  namespace: production
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP 
      nodePort: 30008
  selector:
    app: ladder-client