---
apiVersion: v1 
kind: Service
metadata:
  name: ladder-client
  namespace: production
spec:
  internalTrafficPolicy: Cluster
  ipFamilies: 
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 80
  selector: 
    app.kubernetes.io/instance: ladder-client
    app.kubernetes.io/name: ladder-client
  sessionAffinity: None
  type: NodePort 
  