---
apiVersion: networking.k8s.io/v1beta1 
kind: Ingress
metadata:
  name: ladder-ingress.yaml
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /?(.*)
          backend:
            serviceName: frontend-service
            servicePort: 3000
        - path: /api/?(.*)
          backend:
            serviceName: backend-service
            servicePort: 4000