---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: ladder-ingress
  namespace: prod
  annotations:
    nkubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$
    cert-manager.io/cluster-issuer: "letsencrypt-staging"

spec:
  rules:
  - http:
      paths:
        - path: /?(.*)
          backend:
            serviceName: frontend-service
            servicePort: 3000
        - path: /api/?(.*)
          backend:
            serviceName: backend-service
            servicePort: 4000