---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ladder-ingress
  namespace: prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  creationTimestamp: {}
  generation: 1
spec:
  ingressClassName: traefik
  rules:
  - host: icoolyousuck.com
    http:
      paths:
      - backend:
          service:
            name: ladder-client
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - icoolyousuck.com
    secretName: ladder-tls
status:
  loadBalancer:
    ingress:
    - ip: 192.168.50.11
