--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
namespace: prod
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-deployment
        image: NGINX-DOCKER-IMAGE 
        ports:
        - containerPort: 80
