# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:PVsPqN4htebOnT8OUbIj1g==,iv:jgz04jKWYu4NfkQH6isrFNQh1ROf3xHM5jsoSXWCKKs=,tag:BZovUgdaAP+ifPEt+sBiBg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:o9w6TG6fMG455e15zTETbTtF0So=,iv:XIRiJFHMc3IyWrY6+hU56+ZiMDYDCHuPb/HdQgKembo=,tag:M/P1tMCM9ceN/v9X4nMM1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fk8cpzq0vpmeyrs3x09xdnccfhmcfx65yyf35a0kka9twn8drywscfy3dp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNDk5N0FXakdYRlU3R0F4
            NEFzZlJrRGt5V044ajFXek0vdkU5WVhwZ1JjCnNldlprcXkzL1hodTQ4c2lIejlo
            bE01ZXRaN3pONlkveStVb2gwNE9RRUEKLS0tIFlsbW5DaEgxcXNOU0pBN0hxWFpw
            K3QyN3lTTTBQckhGUmVYY2FZYTc4clEKXQmAYDyDAS+QX9cznNB+KYmzSB1CVsa/
            xE/B0X9rfOBPR5a48VKW1K5WAQnB/gDMgRmT/gdz/SKgyJbCycwtwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-27T17:45:17Z"
    mac: ENC[AES256_GCM,data:NMmWBND2F5i62CvOKj7ud6rtcs3LdKzQRxwLXGeqxC7UO6OMjyr2YkdMXTbTWVa+7EHMDUpcPZWaIaQGNa5vMI3fZQtSKUeEDHna5xDUpiGFPzDbloRoP85KfjWzg7b/FWxlAW/W/pdsxHJLSJnLg8UYHaGTDkOb+Ed5iQkrxCA=,iv:IFmH1pAbEPhmP0d7lJmFeYgnVXaf+9nL//orih/IR2A=,tag:kkV3s8kSDGiULzf9rkOCCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
