# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:I0T8sD+lZ227FYbzIi+36w==,iv:EdkCvwrfi7tGh1WJevMcMRQUskYT6+Lek1AtoKcuxdM=,tag:Vv0lcIw8SXosNnKEulMyVw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:TMN35TjQXsI1HHM9Z1tjcwWZFcs=,iv:I991BowPI9Trky3HYmSJ7Xy8hQ7LmplAR9OLASmts/U=,tag:C6XErqAE+iUAXNflgD3Odw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fk8cpzq0vpmeyrs3x09xdnccfhmcfx65yyf35a0kka9twn8drywscfy3dp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1S0dOVGt3bW1pN0tNOVUr
            c1BFVmIvVmlqSWE1UW1HenEyc0tRdXJkdEYwCm9kSElvZUJUdFdiSWFEZHVYa0xH
            V3BzbE5FblFONkp5RmhjYWw0Nm9LQVUKLS0tIEVKbDhsbWx3YlBlQVBNaXBEUW4w
            UkVDVXg3TUs5UHVSNENpdnBaS0RrYUkKsHodBNtTqyyPXBSgoynF8QCbbOkv+X/l
            onsmcFE3jqNrmoOGGiCQOpGDNrQU6LvRUgsb44vzvfY9srP1HgeWHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-24T00:30:57Z"
    mac: ENC[AES256_GCM,data:SjftuSYoZIALvJLGUvEwUaouurfcQPDpyEuSFyNh547HTYlyY+f3cvP/19QxtCP+9+R2Imuph0YcU29z73ZbnQAHcWGILDJD15xyAgR0oy9cV4XkHCYdMkETcDU1hetel9+HDuuKDJtT1oD35RV8epDckQAXMrhBYZ0XskGJPDE=,iv:sWPPI+A7CggZo/SCeluCTAmV9ngZcKR1kINUmXxgKt0=,tag:Uhb8oyysm+d4N1nPlo7VeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
