# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:sYgpuXJ8uJ1CpSurhjWbeg==,iv:vEAdWwopE5x5m3I6dYa+aPNkJIkw6xmp+u+u0utbhjU=,tag:mYVm7kkxUeSaQj9hvEDPqg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:+b0myVrDTAtnMOMVgBSTRqpVnOo=,iv:9KiyiiqM7aFfPXAmZtpzTrP3USWGYaOdZez+ZCJMHV0=,tag:LK98tpfBMK2c9c/dLtYqtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vd5j7kge9c8w8t3aj3ekk4gp98fxhaqaptj224yl9aq3nekns30qneex5d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdlhiTk1GVzV6MnVzV21w
            aW9PQk93K3NVREdEUHcrYXZFV0lEUEMyZnpBClVUcExTRmphZjVpR3U1S1prSGdR
            NFU4U1ZYNTlXR3pQRWRhd1YyMXAyNkUKLS0tIEdCSEx3c3k1UXUwYmJUOTNaTW0r
            SlpmcHVLSVBuMWpOcUYrT1Bsd2ZqM28KWjEKgdRT9+GCwl4L/zGknMGWjlybSRoE
            1uOjHDDyU64HKlmjlFHGgSOZXwoLd9FMGy/XpCalekV6IYBx/LvN/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-05T23:53:05Z"
    mac: ENC[AES256_GCM,data:f/CeXslGGSl/P1U/71OSoqgKsRJw2USQU8ClJm39HtpiZesMl4lRNzzU6Vg7yQcJO2w+r2ORqdaYkJufJdTmF3KbMcA4nWhB1MwBWoEKuUjuKu4LydugcLlWnYCLwt3mVAe20/7jKOwH8Qqc/l6AafRGt9l1NZJl484JDZDJfDs=,iv:S8YZk+nyxoMEzGZ2t+R6uNRBlsWafmanjN+hItSw3So=,tag:OmFwyFoRbrv7FVCPg6HWsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
