---
- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: nuke

- name: Reboot Servers
  hosts: node, master
  gather_facts: no
  become: true
  tasks:
    - name: Reboot machine
      reboot:
        reboot_timeout: 200