apiVersion: v1
data:
    discord-webhook: ENC[AES256_GCM,data:UgCp3fV7AQWWWr9tMYww0g6ouRE8o8XPwUe2JIEmHdDoAaPcazFN9it508ZVl44uHK/8cCARUvXKCVEXiINMIM0PKUcNuStti2HXxU/5796fg4RzwQnds8Abprmu4aNpwA2qussJ1vjxuyXOcxwGa9iYmM8zJaSY,iv:vosunP1fxx/2pjKH1la+yTuEcrTbtQOP2lpa7nJtoqE=,tag:d9yh5+LsEVII322hpmt1Ng==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: prometheus
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m3hvf7e58692g982nvz4zul9f2ck5azhnfjzr3pngj4esv532c9q022x5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFN1RwOUV5Vmg1a25oeXhQ
            VUluaGdxVEc5VzVRVlNRc2V5RjJ1VDBzdUhRCkdiOHRzQ3BxQXdKSS9qSFhPSnc5
            YVlLRmVwSnNTQ2hCUWVrYS9CRDMyeUUKLS0tIERaMXVtYk1hTDNKeVd4ekRwcHJL
            dGcwcVA3d3QwTERnRXhZbjRTenl6M00KtQFuUQyZ1vKV9qpyAq6wkOv4EJquiRb2
            HUlc9mBGvNC1QVZMqtfk5PIJlSVmHJ65u92zHnQj3RyvWbWeMth3Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-14T23:49:15Z"
    mac: ENC[AES256_GCM,data:AEOAvznzHA4Jjs4J8H3WXxBiSVcYCBPUIqwT6K9i6HT/TXCJla5m07lzrsZAxwVDxkv6W32rFbabOcmWyzDUC2q/foV4HuJ5bB3tDUXCQjAhzVPo/RmYKI++0U5y4zrsoGkaHSMbKW9aiHWs+QexSRr2zO99BuREA6PWTOSQK0I=,iv:FFryLcykrcRMsr8wy4U5oQ2+ieSqXByfOuW5p3MOjJ0=,tag:xg3O+ddb3IBbtOWPjjP8sQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
