---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kuberenetes.io/name: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: mcclaren00/ladder-toolbox-client:latest
        name: ladder-toolbox-client
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        resources: {}
      restartPolicy:  Always
status: {}