---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: prod
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000 # between 30k and 32k

