---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: prod
spec:
  selector:
    app: frontend
    component: web 
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP

