config:
  ## Resources you want to watch
  resources:
  - name: v1/pods        # Name of the resource. Resource name must be in 
                         # group/version/resource (G/V/R) format
                         # resource name should be plural
                         # (e.g apps/v1/deployments, v1/pods)
    namespaces:          # List of namespaces, "all" will watch all the namespaces
      include:
      - all
      ignore:            # List of namespaces to be ignored, used only with include: all
      - kube-system      # example : include [all], ignore [x,y,z]
    events:              # List of lifecycle events you want to receive,
                         # e.g create, update, delete, error OR all
    - create
    - delete
    - error
  - name: batch/v1/jobs
    namespaces:
      include:
      - ns1
      - ns2
    events:
    - create
    - update
    - delete
    - error
    updateSetting:
      includeDiff: true
      fields:
      - spec.template.spec.containers[*].image
      - status.conditions[*].type