apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
  namespace: botkube
spec:
  interval: 5m
  chart: infracloudio-charts
    spec:
      chart: botkube
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: infracloudio-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
    values:
      args:
        - communications.webhook.enabled=true 
        - communications.webhook.url=discord-url
        - config.settings.clustername=anton