---
- name: Update max_user_watches
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: "65536"
    state: present
    sysctl_file: /etc/sysctl.d/98-kubernetes-fs.conf

- name: siable swap runtime
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: diable swap
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none
