---

- name: enable kernel modules at runtime
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - br_netfilter
    - overlay
    - rbd

- name: enable kernel modules at boot
  ansible.builtin.copy:
    mode: 0644
    content: "{{ item }}"
    dest: "/etc/modules-load.d/{{ item }}.conf"
  loop:
   - br_netfilter
   - overlay
   - rbd