---
# - name: Upgrade all system packages
#   ansible.builtin.apt:
#     upgrade: full
#     update_cache: true

- name: Install common packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - arptables
      - ebtables
      - ca-certificates
      - curl
      - ebtables
      - gdisk
      - hdparm
      - htop
      - iputils-ping
      - ipvsadm
      - lvm2
      - nano
      - net-tools
      - nfs-common
      - nvme-cli
      - open-iscsi
      - psmisc
      - smartmontools
      - socat
      - software-properties-common
      - unattended-upgrades
      - unzip
    install_recommends: false

- name: Test for Raspbian
  stat:
    path: /boot/cmdline.txt
  when: "'raspi' in ansible_kernel"

- name: Activating cgroup on Raspbian
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^(.*rootwait)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  when:
    - cmdline.stat.path is defined
    - ansible_facts.architecture is search("arm")
  register: boot_cmdline

- name: Rebooting on Raspbian
  reboot:
  when:
    - boot_cmdline is changed
    - ansible_facts.architecture is search("arm")

- name: Restart node if necessary
  ansible.builtin.meta: flush_handlers