---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord
  namespace: monitoring
spec:
  type: discord
  # username: fluxbot
  channel: alerts
  env:
    - name: discord-webhook
      valueFrom:
        secretKeyRef:
          name: discord-webhook
          key: webhook
          namespace: monitoring
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: on-call-webapp
  namespace: monitoring
spec:
  summary: "anton"
  providerRef:
    name: discord
  eventSeverity: error
  eventSources:
    - kind: HelmRelease
      name: "*"
    - kind: Kustomization
      name: "*"
    - kind: GitRepository
      name: "*"
  exclusionList:
    - "waiting.*socket"
  suspend: false