apiVersion: v1
data:
    address: ENC[AES256_GCM,data:OPGm0pX3+Un6esus6yFHf6x+WKMZm7k7k3br0SSgZLwEKDJmdTm1SRd7+j8RuOE6T71NxxywerPKdDFSafL5PNKMpOxcuW1a+orC0K7jykLNDE9JskeZOutfZZFuvFz8CzfFjn5X9W6x0gDpz1fo98XWPNumKg2D,iv:25brjfX7RORwTYYibDH1hEP4zdNFYr9MDupOhtiw7w0=,tag:Yg4j/hUVVzmWBXb5Vgs+zw==,type:str]
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m3hvf7e58692g982nvz4zul9f2ck5azhnfjzr3pngj4esv532c9q022x5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SjhPdDdtaXBZSnhPRFYr
            NnlESXNMdW8zV2ZaOEN1MGV2a3krdVBrNVFFCjNUd1hyRTZIUUl3VjdZN25IR0Ri
            TUt4OGNSSGNORmdublB3WGJSVHVXdWsKLS0tIGlkS0orRWtBU0NUZnJVNVlaVzla
            YzBOOFBMaUNMc2RpSmR4cVlhOStveHcKHU6lEki8JRBCC4d5uTdP/A5BEXNjBkX+
            4MdH13K3IRnzsSdF7dzr4qZwrswYzfJi64K9Bo2o9qfs0bEd7zxeTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-27T17:14:30Z"
    mac: ENC[AES256_GCM,data:VVwsR/VZyvwHED1oXenMdFwx/q/NlCqnSpn8NctJsNF6DqVTYLrj4xHCA6VP6Yv04+0W6SuGJmFQn7Eul3QgcNXF2rdXVqatKiVu3zXCgUfF5hrHqDZMzp53w+RxacVS4fNFMQ0LEkYMsm4IuPAC0FIkalqMFi0VEgdYlLYX8b8=,iv:dg0WT0s8HWYkf0BOKoR1f0FqJnOV4si+xcxFzaiNEtM=,tag:w0hcE9kcwMmPsgtjhWsYZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
