---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multi
  name: multi-deployment
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi
  strategy: {}
  template:
    metadata:
      labels:
        app: multi
    spec:
      containers:
      - image: mcclaren00/ladder-toolbox-client:latest
        name: ladder-toolbox-client
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        resources: {}
      - image: mcclaren00/ladder-toolbox-server:latest
        name: ladder-toolbox-server 
        imagePullPolicy:  Always
        ports: 
          - containerPort: 4000
        resources: {}
      restartPolicy:  Always
status: {}