--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      containers:
        - name: backend
          image: mcclaren00/ladder-toolbox-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
      restartPolicy: Always
 