--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: prod
spec:
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      containers:
        - name: backend
          image: mcclaren00/ladder-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
      restartPolicy: Always
