---
apiVersion: v1
kind: Service 
metadata:
  name: backend-service
  namespace: prod
  labels: 
    app: backend
spec: 
  selector: 
    app: backend
  type: ClusterIP
  ports: 
  - prototcol: TCP
    port: 4000
    targetPort: 4000