# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:UC2YVxDmxPsFtkS6Flf5Xw==,iv:YmCe2UkvOZo7Y7p0JDJ2GEinvDazqXL6BuLDO3PHDPo=,tag:BGIKV2nZd4S5ottV2KEspw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:X52U24GnPkcupiZ4hqmKpnIjFp0=,iv:irECrw+UAT+ITLbCxWWgcjef2Xx7H2aPVuy+Uz17PPs=,tag:3txrPpuo67J6gZasAONEmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m3hvf7e58692g982nvz4zul9f2ck5azhnfjzr3pngj4esv532c9q022x5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWkZ0QWNWdWRsbzBBYlph
            UCtLbktidDZlWEhtb1Bpbk84RURaQzN4ZlFZCmFJS3RkSE10Qmw0dTZIVHBVR0tH
            aWlDeTgzQmpGbXgzS2FHSFBsY1JHUVkKLS0tIEdJY3ZDT0xvNXpkY0RhUVpab2xm
            YStXbVdSdTd5TVpnZ2JYcUYrcGk1djgKauCQMjXOzmYyLkWi7PUcgjQaQjHVBGRM
            aS9THvV9PaOxmXsgS33y1Oe9vGKLoo3KSXJmsC2TtiQUL8+tI8pGNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-13T18:03:04Z"
    mac: ENC[AES256_GCM,data:whmW+MPieM7gYZWc9bcilHypiTDZ3a7bvK87NYleWSpeMhDLJatoP3uddBo+Lb3lzHDmSZ91ShpaYzCyp01fKph0TJFzj4q8ShD58H+DNLYJ7iV9ZMQLYSGX3CwiJFCDG0TkH4NTInWgQedrsjmYzVLUht7nbE6cAUupHEEQIuU=,iv:f5wRWXzQy0hRuL1h48LQJT4Psify7BxqYMAyF0XJ5ss=,tag:nEpBmJvFJg4eoQWriTvsTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
